import * as yaml from 'js-yaml';
import { ResolutionEntry, DBResolution, ProcedureResolution, ShellResolution } from '../models/types';

export class YamlGenerator {
    
    /**
     * Generate YAML content from resolution entries in manual_mappings_sample.yaml format
     */
    static generateYaml(entries: ResolutionEntry[]): string {
        const currentTimestamp = new Date().toISOString();
        
        // Build YAML structure matching manual_mappings_sample.yaml format
        const yamlData: any = {
            db_operations: [],
            procedure_calls: [],
            shell_executions: []
        };

        // Add entries to appropriate arrays
        for (const entry of entries) {
            const entryData = this.formatEntry(entry, currentTimestamp);
            
            if (entry.type === 'db') {
                yamlData.db_operations.push(entryData);
            } else if (entry.type === 'procedure') {
                yamlData.procedure_calls.push(entryData);
            } else if (entry.type === 'shell') {
                yamlData.shell_executions.push(entryData);
            }
        }

        // Clean up empty arrays
        if (yamlData.db_operations.length === 0) {
            delete yamlData.db_operations;
        }
        if (yamlData.procedure_calls.length === 0) {
            delete yamlData.procedure_calls;
        }
        if (yamlData.shell_executions.length === 0) {
            delete yamlData.shell_executions;
        }

        // Add header comment
        let yamlContent = '# Grey Area Resolution Configuration\n';
        yamlContent += '# ====================================\n';
        yamlContent += '# Auto-generated by Batch KG Gap Analyzer VS Code Extension\n';
        yamlContent += '# This file contains manual mappings for UNKNOWN/DYNAMIC/PARAMETERIZED operations\n\n';
        
        yamlContent += yaml.dump(yamlData, {
            indent: 2,
            lineWidth: 120,
            noRefs: true,
            sortKeys: false
        });

        return yamlContent;
    }

    /**
     * Format a single entry matching manual_mappings_sample.yaml format
     */
    private static formatEntry(entry: ResolutionEntry, timestamp: string): any {
        const entryData: any = {
            method_fqn: entry.method_fqn
        };

        if (entry.type === 'db') {
            const dbRes = entry.resolution as DBResolution;
            if (dbRes.operation_type) entryData.operation_type = dbRes.operation_type;
            if (dbRes.table_name) entryData.table_name = dbRes.table_name;
            if (dbRes.schema_name) entryData.schema_name = dbRes.schema_name;
            if (dbRes.confidence) entryData.confidence = dbRes.confidence;
            
            // Generic fields if present
            if (dbRes.bean_id) entryData.bean_id = dbRes.bean_id;
            if (dbRes.tasklet_fqn) entryData.tasklet_fqn = dbRes.tasklet_fqn;
            if (dbRes.reader_fqn) entryData.reader_fqn = dbRes.reader_fqn;
            if (dbRes.writer_fqn) entryData.writer_fqn = dbRes.writer_fqn;
            if (dbRes.processor_fqn) entryData.processor_fqn = dbRes.processor_fqn;
        } else if (entry.type === 'procedure') {
            const procRes = entry.resolution as ProcedureResolution;
            if (procRes.procedure_name) entryData.procedure_name = procRes.procedure_name;
            if (procRes.schema_name) entryData.schema_name = procRes.schema_name;
            if (procRes.package_name) {
                entryData.package_name = procRes.package_name;
            } else {
                entryData.package_name = null;
            }
            if (procRes.database_type) entryData.database_type = procRes.database_type;
            if (procRes.is_function !== undefined) entryData.is_function = procRes.is_function;
            if (procRes.confidence) entryData.confidence = procRes.confidence;
            
            // Generic fields if present
            if (procRes.bean_id) entryData.bean_id = procRes.bean_id;
            if (procRes.tasklet_fqn) entryData.tasklet_fqn = procRes.tasklet_fqn;
        } else if (entry.type === 'shell') {
            const shellRes = entry.resolution as ShellResolution;
            if (shellRes.script_name) entryData.script_name = shellRes.script_name;
            if (shellRes.script_path) entryData.script_path = shellRes.script_path;
            if (shellRes.script_type) entryData.script_type = shellRes.script_type;
            
            // Remote execution fields (optional)
            if (shellRes.remote_host) {
                entryData.remote_host = shellRes.remote_host;
            } else {
                entryData.remote_host = null;
            }
            if (shellRes.remote_user) entryData.remote_user = shellRes.remote_user;
            if (shellRes.remote_port) entryData.remote_port = shellRes.remote_port;
            if (shellRes.ssh_key_location) entryData.ssh_key_location = shellRes.ssh_key_location;
            if (shellRes.confidence) entryData.confidence = shellRes.confidence;
            if (shellRes.description) entryData.description = shellRes.description;
            
            // Generic fields if present
            if (shellRes.bean_id) entryData.bean_id = shellRes.bean_id;
            if (shellRes.tasklet_fqn) entryData.tasklet_fqn = shellRes.tasklet_fqn;
        }

        // Add metadata to each entry
        entryData.generated_by = 'Batch KG Gap Analyzer Extension';
        entryData.generated_at = timestamp;

        return entryData;
    }

    /**
     * Get filename with today's date
     */
    static getFilenameWithDate(): string {
        const today = new Date();
        const year = today.getFullYear();
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const day = String(today.getDate()).padStart(2, '0');
        return `grey_area_resolution_${year}-${month}-${day}.yaml`;
    }

    /**
     * Check if entry already exists in data (duplicate check)
     */
    private static isDuplicate(entry: any, existingEntries: any[]): boolean {
        if (!existingEntries || existingEntries.length === 0) {
            return false;
        }

        return existingEntries.some(existing => {
            // Check method_fqn first
            if (existing.method_fqn !== entry.method_fqn) {
                return false;
            }

            // Deep equality check for all other fields (excluding metadata)
            const entryWithoutMeta = { ...entry };
            delete entryWithoutMeta.generated_by;
            delete entryWithoutMeta.generated_at;

            const existingWithoutMeta = { ...existing };
            delete existingWithoutMeta.generated_by;
            delete existingWithoutMeta.generated_at;

            return JSON.stringify(entryWithoutMeta) === JSON.stringify(existingWithoutMeta);
        });
    }

    /**
     * Merge new YAML content with existing YAML content
     * Checks for duplicates before adding entries
     */
    static mergeYaml(existingYaml: string, newEntries: ResolutionEntry[]): string {
        let existingData: any = {
            db_operations: [],
            procedure_calls: [],
            shell_executions: []
        };
        
        if (existingYaml.trim()) {
            try {
                existingData = yaml.load(existingYaml) || existingData;
                // Ensure arrays exist
                if (!existingData.db_operations) existingData.db_operations = [];
                if (!existingData.procedure_calls) existingData.procedure_calls = [];
                if (!existingData.shell_executions) existingData.shell_executions = [];
            } catch (error) {
                console.error('Error parsing existing YAML:', error);
            }
        }

        const currentTimestamp = new Date().toISOString();
        let addedCount = 0;
        let duplicateCount = 0;

        // Process new entries and check for duplicates
        for (const entry of newEntries) {
            const entryData = this.formatEntry(entry, currentTimestamp);
            
            if (entry.type === 'db') {
                if (!this.isDuplicate(entryData, existingData.db_operations)) {
                    existingData.db_operations.push(entryData);
                    addedCount++;
                } else {
                    duplicateCount++;
                }
            } else if (entry.type === 'procedure') {
                if (!this.isDuplicate(entryData, existingData.procedure_calls)) {
                    existingData.procedure_calls.push(entryData);
                    addedCount++;
                } else {
                    duplicateCount++;
                }
            } else if (entry.type === 'shell') {
                if (!this.isDuplicate(entryData, existingData.shell_executions)) {
                    existingData.shell_executions.push(entryData);
                    addedCount++;
                } else {
                    duplicateCount++;
                }
            }
        }

        console.log(`Merge results: ${addedCount} new entries added, ${duplicateCount} duplicates skipped`);

        // Clean up empty arrays
        if (existingData.db_operations.length === 0) {
            delete existingData.db_operations;
        }
        if (existingData.procedure_calls.length === 0) {
            delete existingData.procedure_calls;
        }
        if (existingData.shell_executions.length === 0) {
            delete existingData.shell_executions;
        }

        // Add header comment
        let yamlContent = '# Grey Area Resolution Configuration\n';
        yamlContent += '# ====================================\n';
        yamlContent += '# Auto-generated by Batch KG Gap Analyzer VS Code Extension\n';
        yamlContent += '# This file contains manual mappings for UNKNOWN/DYNAMIC/PARAMETERIZED operations\n';
        yamlContent += `# Last updated: ${currentTimestamp}\n\n`;
        
        yamlContent += yaml.dump(existingData, {
            indent: 2,
            lineWidth: 120,
            noRefs: true,
            sortKeys: false
        });

        return yamlContent;
    }
}
